#!/usr/bin/env python3
import sys
from chiron_runtime.lexer import Lexer
from chiron_runtime.parser import Parser
from chiron_runtime.interpreter import Interpreter, Environment

def run_file(path):
    with open(path) as f:
        code = f.read()

    #print("Main file's code: ", code)

    tokens = Lexer(code).tokenize()
    ast = Parser(tokens).parse()

    #print("Main file's AST:", json.dumps(ast, indent=2))

    interpreter = Interpreter()
    interpreter.interpret(ast)

if __name__ == "__main__":
    if len(sys.argv) != 2:
        print("Usage: chiron <filename.chy>")
        sys.exit(1)
    run_file(sys.argv[1])